# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0' 
      - name: Install deps
        run: |
          sudo apt update && sudo apt install -y unzip curl wget python3-pip ruby ruby-dev rubygems python3-setuptools
          pip3 install wheel
          pip3 install cloudsmith-cli
          sudo gem install --no-document fpm

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Build the app    
        run: |
          sudo mkdir -p /go/src/github.com/digitalbits/go

          export GO111MODULE=on

          sudo cp -Rf ./* /go/src/github.com/digitalbits/go/
          sudo go install github.com/digitalbits/go/services/...
      
      - name: Github Tag Bump
        id: bump_version
        uses: anothrNick/github-tag-action@1.34.0
        env:
          DEFAULT_BUMP: "patch"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false   
      - name: Make .deb package
        run: |
          fpm -f -s dir -t deb -n digitalbits-federation -v ${{ steps.bump_version.outputs.tag }} /home/runner/go/bin/federation=/usr/local/bin/federation 
          fpm -f -s dir -t deb -n digitalbits-friendbot -v ${{ steps.bump_version.outputs.tag }} /home/runner/go/bin/friendbot=/usr/local/bin/friendbot 
          fpm -f -s dir -t deb -n digitalbits-frontier -v ${{ steps.bump_version.outputs.tag }} /home/runner/go/bin/frontier=/usr/local/bin/frontier 
          fpm -f -s dir -t deb -n digitalbits-keystored -v ${{ steps.bump_version.outputs.tag }} /home/runner/go/bin/keystored=/usr/local/bin/keystored 
          fpm -f -s dir -t deb -n digitalbits-loadtest -v ${{ steps.bump_version.outputs.tag }} /home/runner/go/bin/loadtest=/usr/local/bin/loadtest 
          
      - name: Upload to cloudsmith.io
        run: |
          export CLOUDSMITH_API_KEY=${{ secrets.CLOUDSMITH_API_KEY }}
          export PATH=$PATH:/home/runner/.local/bin
          cloudsmith push deb xdb-foundation/digitalbits-federation/ubuntu/focal digitalbits-federation_${{ steps.bump_version.outputs.tag }}_amd64.deb
          cloudsmith push deb xdb-foundation/digitalbits-friendbot/ubuntu/focal digitalbits-friendbot_${{ steps.bump_version.outputs.tag }}_amd64.deb  
          cloudsmith push deb xdb-foundation/digitalbits-frontier/ubuntu/focal digitalbits-frontier_${{ steps.bump_version.outputs.tag }}_amd64.deb  
          cloudsmith push deb xdb-foundation/digitalbits-keystored/ubuntu/focal digitalbits-keystored_${{ steps.bump_version.outputs.tag }}_amd64.deb  
          cloudsmith push deb xdb-foundation/digitalbits-loadtest/ubuntu/focal digitalbits-loadtest_${{ steps.bump_version.outputs.tag }}_amd64.deb  
